steps:
  # 1. Docker 이미지 빌드 (Git 커밋 해시 태그 생성)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/mervis-repo/mervis-core:$COMMIT_SHA',
      '.'
    ]

  # 2. 이미지를 Artifact Registry로 푸시 (생성된 태그 푸시)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'asia-northeast3-docker.pkg.dev/$PROJECT_ID/mervis-repo/mervis-core:$COMMIT_SHA'
    ]

  # 3. 인프라 저장소(mervis_infra) Clone
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/MinDongIl/mervis_infra.git']

  # 4. Terraform 초기화 (GCS 백엔드 상태 파일 연결)
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    dir: 'mervis_infra'  # 다운로드한 인프라 폴더 내부로 진입
    args:
      - '-c'
      - |
        terraform init

  # 5. Terraform Apply (image_tag 변수에 커밋 해시 주입 후 템플릿 갱신 및 롤링 배포 트리거)
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    dir: 'mervis_infra'  # 다운로드한 인프라 폴더 내부로 진입
    args:
      - '-c'
      - |
        terraform apply -auto-approve -var="image_tag=$COMMIT_SHA"

timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY